name: 🎤 Tech Talk Request
description: Request a new technical deep-dive presentation
title: "[Tech Talk] "
labels: ["tech-talk", "tech-talk:intake"]

body:
  - type: input
    id: topic
    attributes:
      label: Tech Talk Topic
      description: Short name used for the directory (e.g., copilot-memory, agent-teams)
      placeholder: "copilot-memory"
    validations:
      required: true

  - type: textarea
    id: source_urls
    attributes:
      label: Source URLs
      description: Documentation, blog posts, or repos to research (one per line)
      placeholder: |
        https://docs.github.com/copilot/...
        https://github.blog/...
    validations:
      required: true

  - type: input
    id: primary_question
    attributes:
      label: Primary Question
      description: The ONE question this tech talk should answer
      placeholder: "e.g., How do I get Copilot assistance without leaving the terminal?"
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      options:
        - Developers
        - Architects
        - DevOps Engineers
        - Technical Leaders
        - Mixed Audience
    validations:
      required: true

  - type: dropdown
    id: duration
    attributes:
      label: Expected Duration
      options:
        - "30 minutes"
        - "45 minutes"
        - "60 minutes"
      default: 0
    validations:
      required: true

  - type: textarea
    id: guidance
    attributes:
      label: Guidance (optional)
      description: Any specific focus areas, capabilities to cover, or constraints?
      placeholder: "e.g., Focus on enterprise scenarios, must include architecture diagrams"
